# Docker Compose for Demo App Development
# Launches navigation-service, management-ui (host), and PostgreSQL for full demo testing

version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: demo-app-postgres
    environment:
      POSTGRES_DB: conversation_ui
      POSTGRES_USER: conversation_user
      POSTGRES_PASSWORD: conversation_pass
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../../infrastructure/docker/postgres/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U conversation_user -d conversation_ui"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    networks:
      - demo-app-network

  # Navigation Service
  navigation-service:
    build:
      context: ../../backend/navigation-service
      dockerfile: Dockerfile
      target: builder
    container_name: demo-app-navigation
    environment:
      SPRING_PROFILES_ACTIVE: local
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: conversation_ui
      DB_USERNAME: conversation_user
      DB_PASSWORD: conversation_pass
      OPENAI_API_KEY: ${OPENAI_API_KEY:-demo-dummy-key}
      OPENAI_ENABLED: ${OPENAI_ENABLED:-false}
    ports:
      - "8081:8081"  # Navigation service port
      - "8082:8082"  # Management/Actuator port
    volumes:
      - ../../backend/navigation-service/src:/app/src:ro
      - ../../backend/navigation-service/target:/app/target
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped
    networks:
      - demo-app-network

  # Management Service (Required by Management UI)
  management-service:
    build:
      context: ../../backend/management-service
      dockerfile: Dockerfile
      target: builder
    container_name: demo-app-management
    environment:
      SPRING_PROFILES_ACTIVE: local
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: conversation_ui
      DB_USERNAME: conversation_user
      DB_PASSWORD: conversation_pass
      OPENAI_API_KEY: ${OPENAI_API_KEY:-demo-dummy-key}
      OPENAI_ENABLED: ${OPENAI_ENABLED:-false}
    ports:
      - "8080:8080"  # Management service port
      - "8083:8081"  # Management/Actuator port (different external port)
    volumes:
      - ../../backend/management-service/src:/app/src:ro
      - ../../backend/management-service/target:/app/target
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped
    networks:
      - demo-app-network

  # Management UI (Host Application for MFEs)
  management-ui:
    build:
      context: ../management-ui
      dockerfile: Dockerfile
      target: builder
    container_name: demo-app-management-ui
    environment:
      NODE_ENV: development
      MANAGEMENT_SERVICE_URL: http://management-service:8080
      NAVIGATION_SERVICE_URL: http://navigation-service:8081
      CHAT_WIDGET_MFE_URL: http://chat-widget-mfe:3002
    ports:
      - "3000:3000"  # Management UI port
    volumes:
      - ../management-ui/src:/app/src:ro
      - ../management-ui/vite.config.ts:/app/vite.config.ts:ro
    depends_on:
      navigation-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    networks:
      - demo-app-network

  # Chat Widget MFE (Micro Frontend)
  chat-widget-mfe:
    build:
      context: ../chat-widget-mfe
      dockerfile: Dockerfile
    container_name: demo-app-chat-widget
    environment:
      NODE_ENV: development
      NAVIGATION_SERVICE_URL: http://navigation-service:8081
    ports:
      - "3002:3002"  # Chat widget MFE port
    volumes:
      - ../chat-widget-mfe/src:/app/src:ro
      - ../chat-widget-mfe/webpack.config.js:/app/webpack.config.js:ro
    depends_on:
      navigation-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002/remoteEntry.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    networks:
      - demo-app-network

volumes:
  postgres_data:
    driver: local

networks:
  demo-app-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.31.0.0/16
