services:
  postgres:
    image: 'pgvector/pgvector:pg16'
    environment:
      - 'POSTGRES_DB=conversation_ui'
      - 'POSTGRES_PASSWORD=conversation_pass'
      - 'POSTGRES_USER=conversation_user'
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - '5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U conversation_user -d conversation_ui"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
